title: 'Rebecca Asiimwe <br><br><br> Portfolio' # your name (or website title) here
subtitle: 'ghg'

description: > # your text below (remove <br> elements if you don't need line breaks)

  I am a Bioinformatician and Data Scientist with over 10 years of extensive experience in Computing, including 7 years of experience in big and complex 
  data analytics, management and visualization. I am keen at developing computational tools, applying statistical methods and leveraging cutting-edge 
  technologies (including machine learning and artificial intelligence) for integrating, managing and analyzing big, complex and high-dimensional datasets to support 
  the elucidation and discovery of hidden patterns, and unknown correlations in data.
  <br><br>
  Experienced in: The analysis of high-dimensional and high-throughput data including next-generation sequencing (NGS) data, data processing, modeling, mining, 
  analysis and visualization, building innovative data-driven tools and systems to solve complex problems in diverse domains, High-Performance Computing Systems, Python, Shell Scripting, C++, Java, R and R Studio, Shiny, Dash and Plotly, GitHub, Git version control, PLINK, 
  GenomeStudio and Database Development and management (MySQL and PostgreSQL).
  <br><br>
  <a href="https://github.com/rasiimwe">View My GitHub Profile</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/asiimwe-rebecca-1906ab13/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
