title: 'Rebecca Asiimwe' # your name (or website title) here
logo: "/images/Becky_Profile.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  
  I am a Bioinformatician and Data Scientist with over 10 years of experience in Computing, including 7 years of experience in big and complex 
  data analytics, management and visualization. I am keen at developing computational tools, applying statistical methods and leveraging cutting-edge 
  technologies (including machine learning and artificial intelligence) for integrating, managing and analyzing big, complex and high-dimensional datasets to support 
  the elucidation and discovery of hidden patterns, and unknown correlations in biological and clinical data.
  <br><br>
  Experienced in: The analysis of high-dimensional and high-throughput data including next-generation sequencing (NGS) data, data processing, modeling, mining, analysis and visualization, 
  building analytics pipelines and innovative data-driven tools and systems to solve complex problems in diverse domains, High Performance Cluster Computing, Python (Pandas, Numpy, Seaborn, Matplotlib, Scikit-learn, 
  Keras, TensorFlow), Shell Scripting, Command Line Interface, Jupyter Notebook, Google Colab, Anaconda, R, RStudio, Shiny, Plotly, GitHub, GIT Version Control, Database Development, 
  management and optimization (MySQL and PostgreSQL), Standard NGS Bioinformatics Toolsets, PLINK, GenomeStudio, Cell Ranger and Space Ranger.
  <br><br>
  <a href="https://github.com/rasiimwe">GitHub Profile</a> 
  <br>
  <a href="https://github.com/rasiimwe/Code_Examples">Code Examples</a>
  
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
#<-- logo: "/images/Becky_Profile.jpg?raw=true" # your photo (or logo) here -->

